server:
    port: 10000
zuul:
    ignoredServices: '*'
    routes:
        image: /img/**
        catalog: /catalog/**
        onlinestore: /**

security:
    user:
        password: none
    oauth2:
        client:
            accessTokenUri: http://localhost:10003/user/oauth/token
            userAuthorizationUri: http://localhost:10003/user/oauth/authorize
            clientId: onlinestore
            clientSecret: 123456
        resource:
            jwt:
                keyUri: http://localhost:10003/user/oauth/token_key

---
spring:
    profiles: heroku
server:
    port: ${PORT:0}



security:
    oauth2:
        client:
            accessTokenUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/token
            userAuthorizationUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/authorize
            clientId: onlinestore
            clientSecret: 123456
        resource:
            jwt:
                keyUri: https://belajar-springcloud-auth.herokuapp.com/user/oauth/token_key
